/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.itson.migration.clases;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author SaulUrias
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Exportar = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        txtMascota = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btn_file = new javax.swing.JButton();
        txtRutaArchivo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setText("Mascota:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 60, 56, 16);

        jLabel2.setText("Ubicacion:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 110, 66, 16);

        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 150, 42, 16);

        jLabel4.setText("Cliente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 200, 48, 16);

        btn_Exportar.setText("Exportar Ahora");
        btn_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Exportar);
        btn_Exportar.setBounds(90, 260, 240, 29);
        getContentPane().add(txtCliente);
        txtCliente.setBounds(110, 230, 200, 26);
        getContentPane().add(txtMascota);
        txtMascota.setBounds(120, 80, 200, 26);
        getContentPane().add(txtUbicacion);
        txtUbicacion.setBounds(120, 120, 200, 26);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(110, 170, 200, 26);

        btn_file.setText("File");
        btn_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_file);
        btn_file.setBounds(270, 10, 75, 29);
        getContentPane().add(txtRutaArchivo);
        txtRutaArchivo.setBounds(60, 10, 210, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportarActionPerformed
        readXLSX leerExcel = new readXLSX();
        
        String tituloMascota = txtMascota.getText();
        String tituloUbicacion = txtUbicacion.getText();
        String tituloPrecio = txtPrecio.getText();
        String tituloCliente = txtCliente.getText();
        
        try {
            leerExcel.leerValores(txtRutaArchivo.getText(),tituloMascota,tituloUbicacion,tituloPrecio,tituloCliente);
            JOptionPane.showMessageDialog(null, "Datos Exportados");
        } catch (IOException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ExportarActionPerformed

    private void btn_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int ventana = fileChooser.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            txtRutaArchivo.setText(String.valueOf(file));
        }
    }//GEN-LAST:event_btn_fileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exportar;
    private javax.swing.JButton btn_file;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRutaArchivo;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
